
Gui, winner:Add, Picture, x10 y10 w330 h170,%A_ScriptDir%\congratulations.jpg
Gui, winner:Add, Button, x110 y185 w125 h25 +Default gOK, OK
Gui, winner:Show, w351 h217, YOU WIN
return

OK:
Exitapp

winnerGuiClose:
ExitApp
; This Gui is generated by X-GUI Creator